server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:coupon
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO